name: Daily Article Aggregation

on:
  schedule:
    # Run daily at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  aggregate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Articlay
      env:
        GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: |
        python articlay.py --magazines 10 --articles 5
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: daily-articles
        path: articlay-*.json
        retention-days: 30
